name: "CodeSniffer"

on:
  push:
    paths:
      - "**.php"
      - "codesniff.xml"
      - ".github/workflows/codesniff.yml"
  pull_request:
    # The branches below must be a subset of the branches above
    paths:
      - "**.php"
      - "codesniff.xml"
      - ".github/workflows/codesniff.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      # we may use whatever way to install phpcs, just specify the path on the next step
      # however, curl seems to be the fastest
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php" # you may customize glob as needed
          phpcs_path: php phpcs.phar
          standard: codesniff.xml
